### ISSUE TITLE
How to make image clickable without showing the button?

### ISSUE THREAD

**Issue by indrolie** [indrolie/glintstodo#1]
I changed input type="image" to input type="button", but the result was not what I expected.
https://github.com/indrolie/glintstodo/blob/dfe0b358b0911c2b5d9e5dc76c77064010c872c2/index.html#L30-L31

I prefer the search icon on the left than right. See image below.
![screenshot from 2018-07-18 21-39-23](https://user-images.githubusercontent.com/41278410/42888859-521024c2-8ad3-11e8-8346-9c0be707ed7e.png)

**Comment by michaeltamsil** [comment]
already push.
see the link above "issue #1 done" to show what part i changed.
the images below is how to get font icon for search & plus.


![screenshot from 2018-07-18 22-39-39](https://user-images.githubusercontent.com/1217299/42892340-ca2b23b4-8adb-11e8-99cd-d1aa0c46252e.png)
![screenshot from 2018-07-18 22-38-15](https://user-images.githubusercontent.com/1217299/42892341-caa0b35e-8adb-11e8-8a93-39cdd4d2c71c.png)
![screenshot from 2018-07-18 22-38-02](https://user-images.githubusercontent.com/1217299/42892342-cb452204-8adb-11e8-89a9-28dee5f85f6f.png)

to use font icon ..should remember the decimal codes

already push
