### ISSUE TITLE
How to put button inside dropdown list?

### ISSUE THREAD

**Issue by indrolie** [indrolie/glintstodo#2]
I want the button located like picture below.
![screenshot from 2018-07-19 12-07-39](https://user-images.githubusercontent.com/41278410/42922755-5b3d0aaa-8b4c-11e8-8906-643b82d42497.png)

This is my code:
https://github.com/indrolie/glintstodo/blob/6f5ddeeac877dbcad64d2c4a6ffa7278151ba550/index.html#L19-L33

**Comment by mhaidarhanif** [comment]
Revamp the UI and UX flow so it won't be overcomplicated

Look at how Facebook expand the template menu in status box

<img width="514" alt="screen shot 2018-07-19 at 12 58 45" src="https://user-images.githubusercontent.com/235584/42924253-865e4620-8b53-11e8-870c-4f4a0ce2faa9.png">

<img width="519" alt="screen shot 2018-07-19 at 12 58 58" src="https://user-images.githubusercontent.com/235584/42924255-868bd842-8b53-11e8-9628-bf826c2e13ca.png">
